Pets_lovers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages_app.urls'))
]

pages_app/urls.py
from django.urls import path

from pages_app import views

from . import views

app_name = 'pages_app'

urlpatterns = [
    #views para a parte de animais
    path('', views.home, name='home'),
    path('listAnimal', views.AnimalList.as_view(), name='list'),
    path('createAnimal/', views.AnimalCreate.as_view(), name='createAnimal'),
    path('updateAnimal/<int:pk>/', views.AnimalUpdate.as_view(), name='updateAnimal'),
    path('detailAnimal/<int:pk>/', views.AnimalDetail.as_view(), name='detailAnimal'),
    path('deleteAnimal/<int:pk>/', views.AnimalDelete.as_view(), name='deleteAnimal'),

    #views para a parte de usuarios
    path('listaUsuarios/', views.UsuarioList.as_view(), name='listUser'),
    path('createUser/', views.UsuarioCreate.as_view(), name='createUser'),
    path('updateUser/<int:pk>/', views.UsuarioUpdate.as_view(), name='updateUser'),
    path('detailUser/<int:pk>/', views.UsuarioDetail.as_view(), name='detailUser'),
    path('deleteUser/<int:pk>/', views.UsuarioDelete.as_view(), name='deleteUser'),
]

pages_app/models.py
from django.db import models

SEXO_CHOICES=[
    ('m', 'Masculino'),
    ('f', 'Feminino')
]

TIPO_CHOICES=[
    ('g', 'Gato'),
    ('c', 'Cachorro')
]

# Create your models here.
class Usuario(models.Model):
    nome = models.CharField(max_length=30)
    cpf = models.IntegerField(blank=True, null=True)
    telefone = models.IntegerField(blank=True, null=True)
    idade = models.IntegerField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    data_nascimento = models.DateField(blank=True, null=True)
    profissão = models.CharField(max_length=30)

    def __str__(self):
        return self.nome


class Animal(models.Model):
    nome = models.CharField(max_length=20)
    raça = models.CharField(max_length=15)
    data_nascimento = models.DateField(blank=True, null=True)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    observações = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nome

pages_app/forms.py
from django import forms

from pages_app.models import Animal, Usuario

class AnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = '__all__'

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = '__all__'

pages_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from pages_app.models import Animal, Usuario

def home(request):
    return render(request, 'pages_app/home.html')

#views referentes a parte de animais
class AnimalList(ListView):
    model = Animal
    queryset = Animal.objects.all()

class AnimalCreate(CreateView):
    model = Animal
    fields = '__all__'
    success_url = reverse_lazy('pages_app:list')

class AnimalUpdate(UpdateView):
    model = Animal
    fields = '__all__'
    success_url = reverse_lazy('pages_app:list')

class AnimalDetail(DetailView):
    queryset = Animal.objects.all()

class AnimalDelete(DeleteView):
    queryset = Animal.objects.all()
    success_url = reverse_lazy('pages_app:list')

#viwes referentes a parte de usuários
class UsuarioList(ListView):
    model = Usuario
    queryset = Usuario.objects.all()

class UsuarioCreate(CreateView):
    model = Usuario
    fields = '__all__'
    success_url = reverse_lazy('pages_app:listUser')

class UsuarioUpdate(UpdateView):
    model = Usuario
    fields = '__all__'
    success_url = reverse_lazy('pages_app:listUser')

class UsuarioDetail(DetailView):
    queryset = Usuario.objects.all()

class UsuarioDelete(DeleteView):
    queryset = Usuario.objects.all()
    success_url = reverse_lazy('pages_app:listUser')

templates/pages_app/Animal_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Deletar animal</title>
</head>
<body>
    <div>
        Tem certeza que deseja apagar '{{ object.nome}}'?
        <form action="." method="post">
            {% csrf_token %}
            <input type="submit" value="Sim, tenho certeza">
            <input type="reset" onclick="location.href = '{% url 'pages_app:list' %}'" value="Não">
        </form>
    </div>
</body>
</html>

templates/pages_app/Animal_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Detalhes Animal</title>
</head>
<body>
    <div>
        <h2>Informações {{ object.nome }}</h2>
        Raça: {{ object.raça }}
        <br />
        Data de Nascimento: {{ object.data_nascimento }}
        <br />
        Tipo: {{ object.tipo }}
        <br />
        Sexo: {{ object.sexo }}
        <br />
        Observações: {{ object.observações }}
        <br />
        <input type="submit" onclick="location.href = '{% url 'pages_app:list' %}'" value="Voltar">
    </div>
</body>
</html>

templates/pages_app/Animal_form.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Registrar Animais</title>
</head>
<body>
    <div>
        <h1>Cadastrar Animal</h1>
        <form method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Salvar">
            <input type="reset" value="Cancelar" onclick="location.href = '{% url 'pages_app:list' %}' ">
        </form>
    </div>
</body>
</html>

templates/pages_app/Animal_list.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Listagem Animais</title>
</head>
<body>
    <div>
        <h1>Lista de Animais para Adoção</h1>
        <input type="submit" onclick="location.href = '{% url 'pages_app:createAnimal' %}'" value="Cadastrar novo animal">
        <ul>
            {% for animal in object_list %}
            <li><h2>{{ animal.nome }}</h2></li>
            <a href="{% url 'pages_app:updateAnimal' pk=animal.id %}">Editar</a> - 
            <a href="{% url 'pages_app:detailAnimal' pk=animal.id %}">Ver Detalhes</a> - 
            <a href="{% url 'pages_app:deleteAnimal' pk=animal.id %}">Apagar</a>
            {% endfor %}
        </ul>
        <input type="submit" onclick="location.href = '{% url 'pages_app:home' %}'" value="Voltar">
    </div>
</body>
</html>

templates/pages_app/Usuario_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Apagar Usuário</title>
</head>
<body>
    <div>
        Tem certeza que deseja apagar '{{ object.nome}}'?
        <form action="." method="post">
            {% csrf_token %}
            <input type="submit" value="Sim, tenho certeza">
            <input type="reset" onclick="location.href = '{% url 'pages_app:listUser' %}'" value="Não">
        </form>
    </div>
</body>
</html>

templates/pages_app/Usuario_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Detalhes Usuário</title>
</head>
<body>
    <div>
        <h2>Informações {{ object.nome }}</h2>
        CPF: {{ object.cpf }}
        <br />
        Telefone: {{ object.telefone }}
        <br />
        Idade: {{ object.idade }}
        <br />
        Email: {{ object.email }}
        <br />
        Sexo: {{ object.sexo }}
        <br />
        Data de Nascimento: {{ object.data_nascimento }}
        <br />
        Profissão: {{ object.profissão }}
        <br />
        <input type="submit" onclick="location.href = '{% url 'pages_app:listUser' %}'" value="Voltar">
    </div>
</body>
</html>

templates/pages_app/Usuario_form.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Registrar Usuários</title>
</head>
<body>
    <div>
        <h1>Cadastrar Usuário</h1>
        <form method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Salvar">
            <input type="reset" value="Cancelar" onclick="location.href = '{% url 'pages_app:listUser' %}' ">
        </form>
    </div>
</body>
</html>

templates/pages_app/Usuario_list.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Listagem Usuários</title>
</head>
<body>
    <div>
        <h1>Lista de Usuários cadastrados</h1>
        <input type="submit" onclick="location.href = '{% url 'pages_app:createUser' %}'" value="Cadastrar novo usuário">
        <ul>
            {% for usuario in object_list %}
            <li><h2>{{ usuario.nome }}</h2></li>
            <a href="{% url 'pages_app:updateUser' pk=usuario.id %}">Editar</a> - 
            <a href="{% url 'pages_app:detailUser' pk=usuario.id %}">Ver Detalhes</a> - 
            <a href="{% url 'pages_app:deleteUser' pk=usuario.id %}">Apagar</a> 
            {% endfor %}
        </ul>
        <input type="submit" onclick="location.href = '{% url 'pages_app:home' %}'" value="Voltar">
    </div>
</body>
</html>

templates/pages_app/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style_home.css' %}">
    <link rel="icon" href="{% static 'imagens/icon.png' %}">
    <title>Pagina Inicial</title>
</head>
<body>
    <header>
        <div class="capa">
            <img src="{% static 'imagens/capa.png' %}" alt="Imagem de capa" height="50" width="50"><h1>Pet's Lovers</h1>
        </div>
    </header>

    <div class="opcoes"> 
        <a href="{% url 'pages_app:home' %}">HOME</a> | <a >LOGIN</a> | <a href="{% url 'pages_app:listUser' %}">CADASTRE-SE</a> | 
        <a href="{% url 'pages_app:list' %}">CADASTRAR ANIMAL</a>
    </div>

    <footer class="rodape">
        <p>© 2022, PET'S LOVERS. Alguns direitos reservados aos colaboradores.</p>
    </footer>
</body>
</html>